### ISSUE TITLE
long commit sha

### ISSUE THREAD

**Issue by ploctaux** [rob-murray/jekyll-version-plugin#5]
is there a way to get a long commit sha?
either we need to change the file, or make it an option please :)

btw, awesome plugin :)

**Comment by ploctaux** [comment]
my bad, I just had to change the "git rev-parse" command.

an option would be nice still :)

**Comment by rob-murray** [comment]
Yeah, sure, that makes sense - I will add the ability to specify the type of command run via options.

**Comment by ploctaux** [comment]
sweet :)
